CREATE TABLE IF NOT EXISTS config_server (
    config_key VARCHAR(255) NOT NULL PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTIES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATED_ON TIMESTAMP,
    APPLICATION VARCHAR(255),
    PROFILE VARCHAR(255),
    LABEL VARCHAR(255),
    PROP_KEY VARCHAR(255),
    PROP_VALUE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS blog_service (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    author_id VARCHAR(255) NOT NULL,
    post_date TIMESTAMP
);
